[package]
name = "rust_crypt"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_crypt"
crate-type = ["staticlib", "rlib"]

[dependencies]
blowfish = "0.8"
libc = "0.2"
pbkdf2 = "0.12"
hmac = "0.12"
sha2 = "0.10"
