[package]
name = "rust_lua"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.9", features = ["lua54", "vendored"] }
rust_ffi = { path = "../rust_ffi" }
once_cell = "1"

[lib]
name = "rust_lua"
crate-type = ["staticlib", "rlib"]
