[package]
name = "rust_spellsuggest"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_spellfile = { path = "../rust_spellfile" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "compare"
harness = false
