[package]
name = "rust_if_python"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.21", features = ["auto-initialize"] }

[lib]
name = "rust_if_python"
crate-type = ["staticlib", "rlib"]
