[package]
name = "vim_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_editor = { path = "../rust_editor" }
ratatui = { version = "0.26", default-features = false, features = ["crossterm"] }
crossterm = "0.27"

