[package]
name = "rust_drawscreen"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
rust_ui = { path = "../rust_ui" }

[lib]
name = "rust_drawscreen"
crate-type = ["staticlib", "rlib"]
