[package]
name = "rust_message"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
rust_log = { path = "../rust_log" }

[dev-dependencies]
tempfile = "3"
