[package]
name = "rust_version"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "rust_version"
crate-type = ["staticlib", "rlib"]

[dependencies]
once_cell = "1"

[build-dependencies]
