[package]
name = "vim_channel"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["net", "time", "macros", "io-util", "rt"] }
spell = { path = "rust/spell" }
diff = { path = "rust/diff" }
rust_buffer = { path = "rust_buffer" }
rust_os_unix = { path = "rust_os_unix" }

[lib]
name = "vim_channel"
path = "src/channel.rs"
