[package]
name = "vim_channel"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["net", "time", "macros", "io-util", "rt"] }
spell = { path = "rust/spell" }
rust_search = { path = "rust_search" }

[lib]
name = "vim_channel"
path = "src/channel.rs"
