[package]
name = "vim_channel"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["net", "time", "macros", "io-util", "rt"] }
rust_spell = { path = "rust_spell" }
diff = { path = "rust/diff" }
rust_buffer = { path = "rust_buffer" }
rust_if_python = { path = "rust_if_python" }
rust_if_lua = { path = "rust_if_lua" }
rust_profiler = { path = "rust_profiler" }
rust_debugger = { path = "rust_debugger" }
rust_os = { path = "rust_os" }
rust_pty = { path = "rust_pty" }
rust_wayland = { path = "rust_wayland" }

[lib]
name = "vim_channel"
path = "src/channel.rs"
