[package]
name = "vim_channel"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["net", "time", "io-util", "rt", "rt-multi-thread"] }

[lib]
name = "vim_channel"
path = "src/channel/mod.rs"
crate-type = ["staticlib"]
