[package]
name = "rust_netbeans"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "macros"] }

[lib]
name = "rust_netbeans"
crate-type = ["staticlib", "rlib"]
