[package]
name = "rust_xpm_w32"
version = "0.1.0"
edition = "2021"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[lib]
name = "rust_xpm_w32"
crate-type = ["staticlib", "rlib"]
