[package]
name = "vim-channel"
version = "0.1.0"
edition = "2021"

[lib]
name = "vim_channel"
path = "channel.rs"
crate-type = ["staticlib"]

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util" ] }
libc = "0.2"
