use std::fs;
use std::io;
use std::path::Path;

pub fn generate_file<P: AsRef<Path>>(path: P) -> io::Result<()> {
    let path = path.as_ref();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    let content = r#"""
" Vim plugin generated by Rust build step.
" Do not edit manually.

if exists('g:loaded_rust_hello')
  finish
endif
let g:loaded_rust_hello = 1

command! RustHello echo 'Hello from Rust build'
"""#;

    // Only write when content changed to avoid unnecessary rebuild churn.
    let need_write = match fs::read_to_string(path) {
        Ok(existing) => existing != content,
        Err(_) => true,
    };

    if need_write {
        fs::write(path, content)?;
    }
    Ok(())
}

