[package]
name = "rust_search"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_search"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
regex = "1"
once_cell = "1"
rust_highlight = { path = "../rust_highlight" }

[dev-dependencies]
tempfile = "3"
