[package]
name = "rust_window"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1"

[lib]
name = "rust_window"
crate-type = ["staticlib", "rlib"]
[features]
default = ["tty"]
tty = []
gui = []
