[package]
name = "rust_regexp"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
rust_fuzzy = { path = "../rust_fuzzy" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[lib]
name = "rust_regexp"
crate-type = ["staticlib", "rlib"]
