[package]
name = "rust_python"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.21", features = ["auto-initialize"] }
rust_ffi = { path = "../rust_ffi" }

[lib]
name = "rust_python"
crate-type = ["staticlib", "rlib"]
