[package]
name = "vim-crypto-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "vim_crypto_core"
crate-type = ["staticlib"]

[dependencies]
blowfish = "0.8"
pbkdf2 = "0.12"
hmac = "0.12"
sha2 = "0.10"
libc = "0.2"
rust_sha256 = { path = "../../../../rust_sha256" }

[workspace]
