[package]
name = "rust_excmd"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_excmd"
crate-type = ["staticlib", "rlib"]

[dependencies]
rust_change = { path = "../rust_change" }
once_cell = "1"
