[package]
name = "vim_job"
version = "0.1.0"
edition = "2021"

[lib]
name = "vim_job"
crate-type = ["staticlib", "rlib"]

[dependencies]
tokio = { version = "1", features = ["process", "io-util", "rt-multi-thread", "macros", "time"] }
