[package]
name = "rust_clipboard"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(target_os = "windows")'.dependencies]
copypasta = "0.10"

[lib]
name = "rust_clipboard"
crate-type = ["staticlib", "rlib"]
