[package]
name = "rust_clipboard"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(windows)'.dependencies]
copypasta = { version = "0.10" }

[features]
default = []

[lib]
name = "rust_clipboard"
crate-type = ["staticlib", "rlib"]
