[package]
name = "rust_fileio"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
rust_path = { path = "../rust_path" }
tokio = { version = "1", features = ["fs", "macros", "rt"] }

[dev-dependencies]
tempfile = "3"
