[package]
name = "rust_channel"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_channel"
crate-type = ["staticlib", "rlib"]

[dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "net", "io-util"] }

