[package]
name = "rust_ole"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.52", features = ["Win32_System_Com"] }

[lib]
name = "rust_ole"
crate-type = ["staticlib", "rlib"]
