[package]
name = "rust_option"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
rust_optionstr = { path = "../rust_optionstr" }

[build-dependencies]
bindgen = "0.69"

[dev-dependencies]
tempfile = "3"
