[package]
name = "rust_option"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]

config = "0.14"
serde = { version = "1", features = ["derive"] }

[build-dependencies]
bindgen = "0.69"

[dev-dependencies]
tempfile = "3"
