[package]
name = "rust_help"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
rust_window = { path = "../rust_window" }

[dev-dependencies]
tempfile = "3"

[lib]
name = "rust_help"
crate-type = ["staticlib", "rlib"]
