[package]
name = "rust_filepath"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.10"

[dev-dependencies]
tempfile = "3"

[lib]
name = "rust_filepath"
crate-type = ["staticlib", "rlib"]
