[package]
name = "rust_vimrun"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = ["Win32_System_Environment", "Win32_Foundation"] }
