[package]
name = "rust_vimrun"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["shellapi", "winuser"] }

[lib]
name = "rust_vimrun"
crate-type = ["staticlib", "rlib"]
