[package]
name = "rust_os_mswin"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.52", features = ["Win32_System_SystemInformation"] }
libc = "0.2"

[lib]
name = "rust_os_mswin"
crate-type = ["staticlib", "rlib"]
