[package]
name = "rust_textformat"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
rust_text = { path = "../rust_text" }
rust_indent = { path = "../rust_indent" }

[lib]
name = "rust_textformat"
crate-type = ["staticlib", "rlib"]
