[package]
name = "vim_jsonlib"
version = "0.1.0"
edition = "2021"

[lib]
name = "vim_jsonlib"
crate-type = ["staticlib", "rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

