[package]
name = "rust_pty"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.27", features = ["term"] }
tokio = { version = "1", features = ["rt", "net", "time", "macros", "io-util"] }
