[package]
name = "vim_json"
version = "0.1.0"
edition = "2021"

[lib]
name = "json"
crate-type = ["staticlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libc = "0.2"
