[package]
name = "rust_mbyte"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_mbyte"
crate-type = ["staticlib", "rlib"]

[dependencies]
unicode-segmentation = "1.10"
unicode-normalization = "0.1"
